# Generated by Django 4.1.7 on 2023-04-02 19:01

import db.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="user Name"
                    ),
                ),
                (
                    "useremail",
                    models.EmailField(blank=True, max_length=254, unique=True),
                ),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2),
                        default=db.models.empty_list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
